apiVersion: 1

contactPoints:
  - orgId: 1
    name: cargo-pilot-email
    receivers:
      - uid: email-receiver-prod
        type: email
        settings:
          addresses: devops@divizyon.org
          singleEmail: false
        disableResolveMessage: false
